spring:

  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/items;MODE=MYSQL;
    username: order-user
    password: order-pass

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: error