insert into items (item_token, item_no, item_name, price, stock, status) values ('fkzxlgkNQwrk', '782858', '폴로 랄프로렌 남성 수영복반바지 컬렉션 (51color)', '39500', 50, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('FEOrglknrtre', '779989', '버드와이저 HOME DJing 굿즈 세트', '35000', 43, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('lkfmlayieEJR', '779943', 'Fabrik Pottery Flat Cup & Saucer - Mint', '24900', 89, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('LSDKnakstase', '779049', '[리퍼브/키친마켓] Fabrik Pottery Cup, Saucer (단품)', '10000', 64, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('IslktnasehqW', '778422', '캠핑덕 우드롤테이블', '45000', 7, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('QjaskehrAWKj', '768848', '[STANLEY] GO CERAMIVAC 진공 텀블러/보틀 3종', '21000', 45, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('OEKRlsasoeKR', '768110', '네페라 손 세정제 대용량 500ml 이더블유지', '7000', 79, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('dskflNESTLid', '760709', '파버카스텔 연필1자루', '200', 70, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('zlsOAWkLFNAw', '759928', '마스크 스트랩 분실방지 오염방지 목걸이', '2800', 85, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('asdjKEEBrawe', '748943', '디오디너리 데일리 세트 (Daily set)', '19000', 89, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('OPDlkntsakta', '744775', 'SHUT UP [TK00112]', '28000', 35, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('OXCLESnastkl', '706803', 'ZEROVITY™ Flip Flop Cream 2.0 (Z-FF-CRAJ-)', '38000', 81, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('WelKARNudsif', '648418', 'BS 02-2A DAYPACK 26 (BLACK)', '238000', 5, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('Plrnasetlayq', '628066', '무설탕 프로틴 초콜릿 틴볼스', '12900', 8, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('lfdskntsetOI', '611019', '플루크 new 피그먼트 오버핏 반팔티셔츠 FST701 / 7color M', '19800', 7, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('CLFKsentlksE', '517643', '에어팟프로 AirPods PRO 블루투스 이어폰(MWP22KH/A)', '260800', 26, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('FDKSLemsiten', '502480', '[29Edition.]_[스페셜구성] 렉시 브라렛 세트(브라1+팬티2)', '24900', 41, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('ALqakwlnsdfl', '377169', '[29Edition.]_[스페셜구성] 뉴코튼베이직 브라렛 세트 (브라1+팬티2)', '24900', 60, 'ON_SALE');
insert into items (item_token, item_no, item_name, price, stock, status) values ('xclansklrSSr', '213341', '20SS 오픈 카라/투 버튼 피케 티셔츠 (6color)', '33250', 99, 'ON_SALE');
